version: "3.9"

services:
  database: 
    image: postgres
    container_name: database_filmflix
    restart: always
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=filmflix
      - POSTGRES_DB=db_filmflix
    volumes:
      - pgdata:/data/postgres
volumes:
  pgdata:
    driver: local